// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: services/status_master.proto

// 名前衝突を避ける

package statusmaster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StatusMaster_SayHello_FullMethodName = "/todo.StatusMaster/SayHello"
)

// StatusMasterClient is the client API for StatusMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatusMasterClient interface {
	SayHello(ctx context.Context, in *StausRequest, opts ...grpc.CallOption) (*StausResponse, error)
}

type statusMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusMasterClient(cc grpc.ClientConnInterface) StatusMasterClient {
	return &statusMasterClient{cc}
}

func (c *statusMasterClient) SayHello(ctx context.Context, in *StausRequest, opts ...grpc.CallOption) (*StausResponse, error) {
	out := new(StausResponse)
	err := c.cc.Invoke(ctx, StatusMaster_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusMasterServer is the server API for StatusMaster service.
// All implementations must embed UnimplementedStatusMasterServer
// for forward compatibility
type StatusMasterServer interface {
	SayHello(context.Context, *StausRequest) (*StausResponse, error)
	mustEmbedUnimplementedStatusMasterServer()
}

// UnimplementedStatusMasterServer must be embedded to have forward compatible implementations.
type UnimplementedStatusMasterServer struct {
}

func (UnimplementedStatusMasterServer) SayHello(context.Context, *StausRequest) (*StausResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedStatusMasterServer) mustEmbedUnimplementedStatusMasterServer() {}

// UnsafeStatusMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusMasterServer will
// result in compilation errors.
type UnsafeStatusMasterServer interface {
	mustEmbedUnimplementedStatusMasterServer()
}

func RegisterStatusMasterServer(s grpc.ServiceRegistrar, srv StatusMasterServer) {
	s.RegisterService(&StatusMaster_ServiceDesc, srv)
}

func _StatusMaster_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StausRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusMasterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatusMaster_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusMasterServer).SayHello(ctx, req.(*StausRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatusMaster_ServiceDesc is the grpc.ServiceDesc for StatusMaster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatusMaster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todo.StatusMaster",
	HandlerType: (*StatusMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _StatusMaster_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/status_master.proto",
}
